[package]
name = "models"
version = "0.1.0"
authors = ["TheZoq2 <frans.skarman@gmail.com>"]

[dependencies]
scad_generator = {git = "https://github.com/TheZoq2/Rust-Scad.git"}
scad_util = {git = "https://github.com/TheZoq2/Rust-scad-util.git"}
